services:
  - type: web
    name: linkedin-scraper
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: RAPIDAPI_KEY
      - key: RAPIDAPI_HOST
